#!/usr/bin/env python3
"""expertise.py: dashboard and lint for a student expertise vault.

A vault has two zones:

  library/  facts, kept by the agent; every fact cites a source
  mind/     the student's own thinking; the agent reads it and never writes it

The student climbs a ladder: facts -> insights -> positions. Five practices
(play, empathy, creation, experimentation, reflection) are how the student
climbs it. This tool counts the climb and names the next step.

Usage:
  python3 scripts/expertise.py dashboard <vault> [--today YYYY-MM-DD] [--stdout]
  python3 scripts/expertise.py lint <vault>

`dashboard` writes <vault>/_dashboard.md (generated; never edit it by hand).
`lint` prints rule violations and exits 1 if it finds errors.

Standard library only. Python 3.9+.
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

# ---------------------------------------------------------------------------
# Vocabulary
# ---------------------------------------------------------------------------

PRACTICES = ["play", "empathy", "creation", "experiments", "reflection"]
PRACTICE_NAMES = {
    "play": "Play",
    "empathy": "Empathy",
    "creation": "Creation",
    "experiments": "Experimentation",
    "reflection": "Reflection",
}

# EntreComp: Bacigalupo, Kampylis, Punie and Van den Brande (2016),
# EUR 27939 EN, Joint Research Centre of the European Commission.
ENTRECOMP = {
    "1.1": "Spotting opportunities",
    "1.2": "Creativity",
    "1.3": "Vision",
    "1.4": "Valuing ideas",
    "1.5": "Ethical and sustainable thinking",
    "2.1": "Self-awareness and self-efficacy",
    "2.2": "Motivation and perseverance",
    "2.3": "Mobilizing resources",
    "2.4": "Financial and economic literacy",
    "2.5": "Mobilizing others",
    "3.1": "Taking the initiative",
    "3.2": "Planning and management",
    "3.3": "Coping with uncertainty, ambiguity and risk",
    "3.4": "Working with others",
    "3.5": "Learning through experience",
}
ENTRECOMP_AREAS = {"1": "Ideas and opportunities", "2": "Resources", "3": "Into action"}

# Thresholds for nudges. Small on purpose: a nudge should come early.
TOPIC_SOURCES_BEFORE_A_STANCE = 3   # sources on a topic before we ask for a position
INSIGHT_MIN_LINKS = 2               # an insight connects at least two things
UNTESTED_POSITION_DAYS = 21         # a position this old should have met reality
PRACTICE_WINDOW_DAYS = 14           # "recently" for practice balance

GENERATED_HEADER = (
    "<!-- generated by scripts/expertise.py; never edit by hand; "
    "run `python3 scripts/expertise.py dashboard <vault>` -->"
)

WIKILINK = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]*)?(?:\|[^\]]*)?\]\]")
HEADING = re.compile(r"^(#{1,6})\s+(.*)$")


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

def _strip_comment(value: str) -> str:
    """Drop a YAML-style ` # comment` unless the value is quoted."""
    value = value.strip()
    if value[:1] in "\"'":
        return value
    return re.split(r"\s+#", value, maxsplit=1)[0].strip()


def _scalar(value: str):
    value = _strip_comment(value)
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def parse_frontmatter(text: str) -> tuple[dict, str]:
    """Parse a small YAML subset: `key: value`, `key: [a, b]`, and `- item` lists."""
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end == -1:
        return {}, text
    block = text[4:end]
    body = text[end + 4:].lstrip("\n")
    data: dict = {}
    current_list_key = None
    for raw in block.splitlines():
        line = raw.rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line.startswith(("  - ", "- ")) and current_list_key:
            data[current_list_key].append(_scalar(line.split("- ", 1)[1]))
            continue
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        key, value = key.strip(), _strip_comment(value)
        if value == "":
            data[key] = []
            current_list_key = key
            continue
        current_list_key = None
        if value.startswith("[") and value.endswith("]") and not value.startswith("[["):
            inner = value[1:-1].strip()
            data[key] = [_scalar(v) for v in inner.split(",")] if inner else []
        else:
            data[key] = _scalar(value)
    return data, body


def sections(body: str) -> dict[str, str]:
    """Map each `## Heading` (lowercased) to its text."""
    out: dict[str, str] = {}
    current = None
    buf: list[str] = []
    for line in body.splitlines():
        m = HEADING.match(line)
        if m and len(m.group(1)) == 2:
            if current is not None:
                out[current] = "\n".join(buf).strip()
            current = m.group(2).strip().lower()
            buf = []
        elif current is not None:
            buf.append(line)
    if current is not None:
        out[current] = "\n".join(buf).strip()
    return out


def as_list(value) -> list[str]:
    if value is None or value == "":
        return []
    if isinstance(value, list):
        return [str(v).strip() for v in value if str(v).strip()]
    return [str(value).strip()]


def link_name(target: str) -> str:
    return target.strip().split("/")[-1].removesuffix(".md").lower()


def parse_date(value) -> dt.date | None:
    if not value:
        return None
    try:
        return dt.date.fromisoformat(str(value)[:10])
    except ValueError:
        return None


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

@dataclass
class Note:
    path: Path
    rel: str
    zone: str          # library | mind | other
    kind: str          # source, topic, person, insight, position, play, empathy, ...
    name: str
    meta: dict
    body: str
    links: set[str] = field(default_factory=set)
    secs: dict[str, str] = field(default_factory=dict)

    @property
    def created(self) -> dt.date | None:
        return parse_date(self.meta.get("created"))

    @property
    def topics(self) -> list[str]:
        return [t.lower() for t in as_list(self.meta.get("topics"))]

    @property
    def competences(self) -> list[str]:
        return as_list(self.meta.get("entrecomp"))

    def facts(self) -> list[str]:
        text = self.secs.get("facts", "")
        return [l for l in text.splitlines() if l.lstrip().startswith(("- ", "* "))]


def classify(rel_parts: tuple[str, ...]) -> tuple[str, str]:
    if not rel_parts:
        return "other", "other"
    zone = rel_parts[0]
    if zone == "library" and len(rel_parts) >= 3:
        return "library", {"sources": "source", "topics": "topic", "people": "person"}.get(rel_parts[1], "other")
    if zone == "mind" and len(rel_parts) >= 3:
        if rel_parts[1] in ("insights", "positions"):
            return "mind", rel_parts[1][:-1]          # insight | position
        if rel_parts[1] == "practice" and len(rel_parts) >= 4 and rel_parts[2] in PRACTICES:
            return "mind", rel_parts[2]
    return "other", "other"


def load_vault(root: Path) -> list[Note]:
    notes = []
    for path in sorted(root.rglob("*.md")):
        rel_parts = path.relative_to(root).parts
        if any(p.startswith((".", "_")) for p in rel_parts) or rel_parts[0] in ("templates", "skills"):
            continue
        zone, kind = classify(rel_parts)
        if zone == "other":
            continue
        text = path.read_text(encoding="utf-8")
        meta, body = parse_frontmatter(text)
        note = Note(
            path=path,
            rel="/".join(rel_parts),
            zone=zone,
            kind=kind,
            name=path.stem.lower(),
            meta=meta,
            body=body,
        )
        note.links = {link_name(m.group(1)) for m in WIKILINK.finditer(body)}
        for key in ("tests", "from", "topic", "expresses"):
            note.links |= {link_name(v.strip("[]")) for v in as_list(meta.get(key)) if v.startswith("[[")}
        note.secs = sections(body)
        notes.append(note)
    return notes


# ---------------------------------------------------------------------------
# Analysis
# ---------------------------------------------------------------------------

@dataclass
class Report:
    today: dt.date
    counts: dict[str, int]
    facts: int
    topics: list[dict]
    nudges: list[tuple[str, str]]          # (practice or area, message)
    practice_recent: dict[str, int]
    competence_evidence: dict[str, list[str]]
    positions: list[Note]


def analyze(notes: list[Note], today: dt.date) -> Report:
    by_kind: dict[str, list[Note]] = {}
    for n in notes:
        by_kind.setdefault(n.kind, []).append(n)
    by_name = {n.name: n for n in notes}

    def linked_kinds(n: Note) -> list[str]:
        return [by_name[l].kind for l in n.links if l in by_name]

    sources = by_kind.get("source", [])
    insights = by_kind.get("insight", [])
    positions = by_kind.get("position", [])
    experiments = by_kind.get("experiments", [])
    plays = by_kind.get("play", [])

    counts = {k: len(by_kind.get(k, [])) for k in
              ["source", "topic", "person", "insight", "position"] + PRACTICES}
    facts = sum(len(s.facts()) for s in sources)

    # Topics: from topic pages plus any topic named in frontmatter.
    topic_names = {t.name for t in by_kind.get("topic", [])}
    for n in notes:
        topic_names.update(n.topics)
    topics = []
    for t in sorted(topic_names):
        def about(n: Note) -> bool:
            return t in n.topics or t in n.links
        row = {
            "topic": t,
            "sources": sum(1 for s in sources if about(s)),
            "facts": sum(len(s.facts()) for s in sources if about(s)),
            "insights": sum(1 for i in insights if about(i)),
            "positions": sum(1 for p in positions if about(p)),
        }
        topics.append(row)

    nudges: list[tuple[str, str]] = []

    # 1. Facts with no stance: the "200 notes, zero opinions" pattern.
    for row in topics:
        if row["sources"] >= TOPIC_SOURCES_BEFORE_A_STANCE and row["positions"] == 0:
            nudges.append(("Play", f"**{row['topic']}**: {row['sources']} sources and "
                           f"{row['facts']} facts, but no position yet. Write a hypothesis: "
                           f"what do you think is true here that most people would disagree with?"))

    # 2. Insights must connect things.
    for i in insights:
        support = [k for k in linked_kinds(i) if k in ("source", "person", "empathy", "experiments", "insight")]
        if len(support) < INSIGHT_MIN_LINKS:
            nudges.append(("Reflection", f"Insight [[{i.name}]] links {len(support)} thing(s) you know. "
                           f"An insight connects at least {INSIGHT_MIN_LINKS}: which facts made you see it?"))

    # 3. Positions need a way to be wrong, and a meeting with reality.
    tested = set()
    for e in experiments:
        tested |= {l for l in e.links if l in by_name and by_name[l].kind == "position"}
    for p in positions:
        change = p.secs.get("what would change my mind", "").strip()
        if not change or change.startswith("<!--"):
            nudges.append(("Reflection", f"Position [[{p.name}]] has no answer to "
                           f"*What would change my mind?* A position you can't lose isn't a position yet."))
        because = [k for k in linked_kinds(p) if k in ("insight", "source", "person", "empathy", "experiments")]
        if not because:
            nudges.append(("Reflection", f"Position [[{p.name}]] links nothing you know. "
                           f"Link the insights or facts behind it."))
        created = p.created
        if p.name not in tested and created and (today - created).days > UNTESTED_POSITION_DAYS:
            nudges.append(("Experimentation", f"Position [[{p.name}]] is {(today - created).days} days old "
                           f"and has never been tested. Design the cheapest test that could prove it wrong."))

    # 4. Hypotheses past their check date.
    for h in plays:
        if str(h.meta.get("type", "")).lower() != "hypothesis":
            continue
        check_by = parse_date(h.meta.get("check_by"))
        result = str(h.meta.get("result", "open")).lower()
        if check_by and check_by < today and result in ("", "open"):
            nudges.append(("Experimentation", f"Hypothesis [[{h.name}]] was due to be checked on "
                           f"{check_by.isoformat()}. Was it supported? Set `result:` and say what you learned."))

    # 5. Practice balance.
    window_start = today - dt.timedelta(days=PRACTICE_WINDOW_DAYS)
    practice_recent = {p: 0 for p in PRACTICES}
    for n in notes:
        if n.kind in PRACTICES and n.created and window_start <= n.created <= today:
            practice_recent[n.kind] += 1
    advice = {
        "play": "Go exploring: follow one curiosity with no goal, or write a hypothesis before you read the answer.",
        "empathy": "Talk to someone who lives this problem. Ask about the last time it happened, not about your idea.",
        "creation": "Make something from what you know: a post, a sketch, a prototype. Show it to one person.",
        "experiments": "Test a hypothesis or a position. What is the smallest thing you could try this week?",
        "reflection": "Write this week's reflection. What changed your mind?",
    }
    for p, count in practice_recent.items():
        if count == 0:
            nudges.append((PRACTICE_NAMES[p], f"No {PRACTICE_NAMES[p].lower()} in the last "
                           f"{PRACTICE_WINDOW_DAYS} days. {advice[p]}"))

    # 6. EntreComp evidence (student work only).
    competence_evidence: dict[str, list[str]] = {c: [] for c in ENTRECOMP}
    for n in notes:
        if n.zone != "mind":
            continue
        for c in n.competences:
            if c in competence_evidence:
                competence_evidence[c].append(n.name)

    return Report(today, counts, facts, topics, nudges, practice_recent, competence_evidence,
                  sorted(positions, key=lambda p: p.name))


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

def render_dashboard(r: Report) -> str:
    c = r.counts
    out = [GENERATED_HEADER, "", f"# Dashboard — {r.today.isoformat()}", ""]
    out += ["## The ladder", "",
            "| Facts (library) | Insights (yours) | Positions (yours) |",
            "|---|---|---|",
            f"| {r.facts} facts from {c['source']} sources | {c['insight']} | {c['position']} |", ""]
    if c["position"]:
        out.append(f"{r.facts / c['position']:.0f} facts per position.")
    else:
        out.append("No positions yet. Every expert has opinions; this is where yours will go.")
    out.append("")
    if r.topics:
        out += ["## Topics", "", "| Topic | Sources | Facts | Insights | Positions |", "|---|---|---|---|---|"]
        for t in r.topics:
            gap = " ⚠" if t["sources"] >= TOPIC_SOURCES_BEFORE_A_STANCE and t["positions"] == 0 else ""
            out.append(f"| {t['topic']}{gap} | {t['sources']} | {t['facts']} | {t['insights']} | {t['positions']} |")
        out.append("")
    out += ["## Next steps", ""]
    if r.nudges:
        for practice, message in r.nudges:
            out.append(f"- **{practice}** — {message}")
    else:
        out.append("- Nothing flagged. Pick a position and try to break it.")
    out.append("")
    out += [f"## Practice in the last {PRACTICE_WINDOW_DAYS} days", "",
            "| " + " | ".join(PRACTICE_NAMES[p] for p in PRACTICES) + " |",
            "|" + "---|" * len(PRACTICES),
            "| " + " | ".join(str(r.practice_recent[p]) for p in PRACTICES) + " |", ""]
    if r.positions:
        out += ["## Your positions", "", "| Position | Confidence | Status |", "|---|---|---|"]
        for p in r.positions:
            out.append(f"| [[{p.name}]] | {p.meta.get('confidence', '?')} | {p.meta.get('status', 'draft')} |")
        out.append("")
    out += ["## EntreComp evidence", "",
            "Competences from the European Commission's EntreComp framework, with the notes in `mind/` "
            "that show them. Evidence, not a grade.", ""]
    for area, area_name in ENTRECOMP_AREAS.items():
        out.append(f"**{area}. {area_name}**")
        out.append("")
        for code, name in ENTRECOMP.items():
            if not code.startswith(area + "."):
                continue
            ev = r.competence_evidence[code]
            shown = ", ".join(f"[[{e}]]" for e in ev[:4]) + (f" +{len(ev) - 4}" if len(ev) > 4 else "")
            out.append(f"- {code} {name}: {len(ev)}" + (f" — {shown}" if ev else ""))
        out.append("")
    return "\n".join(out).rstrip() + "\n"


@dataclass
class Finding:
    level: str  # error | warning
    rel: str
    message: str


def lint(notes: list[Note], root: Path) -> list[Finding]:
    findings: list[Finding] = []
    names = {n.name for n in notes}
    extra = {p.stem.lower() for p in root.rglob("*.md")}
    for n in notes:
        written_by = str(n.meta.get("written_by", "")).lower()
        if n.zone == "mind" and written_by and written_by != "me":
            findings.append(Finding("error", n.rel, f"`written_by: {written_by}` in mind/. "
                                    "Only the student writes in mind/."))
        if n.zone == "mind" and not written_by:
            findings.append(Finding("warning", n.rel, "missing `written_by: me`."))
        if n.kind == "source":
            if not (n.meta.get("url") or n.meta.get("from")):
                findings.append(Finding("error", n.rel, "source with no `url:` or `from:`. "
                                        "Every fact needs a place it came from."))
            if not n.facts():
                findings.append(Finding("warning", n.rel, "source with no bullets under `## Facts`."))
        if n.kind == "position":
            for required in ("i believe", "because", "what would change my mind"):
                if required not in n.secs:
                    findings.append(Finding("error", n.rel, f"position without `## {required.capitalize()}`."))
            conf = n.meta.get("confidence")
            if conf not in (None, "") and not (str(conf).isdigit() and 0 <= int(conf) <= 100):
                findings.append(Finding("error", n.rel, f"`confidence: {conf}` must be 0-100."))
        for code in n.competences:
            if code not in ENTRECOMP:
                findings.append(Finding("error", n.rel, f"unknown EntreComp code `{code}` (use 1.1-3.5)."))
        for link in sorted(n.links):
            if link not in names and link not in extra:
                findings.append(Finding("warning", n.rel, f"link to missing note [[{link}]]."))
        if n.created is None:
            findings.append(Finding("warning", n.rel, "missing or invalid `created: YYYY-MM-DD`."))
    return findings


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    d = sub.add_parser("dashboard", help="write <vault>/_dashboard.md")
    d.add_argument("vault", type=Path)
    d.add_argument("--today", help="YYYY-MM-DD (default: today)")
    d.add_argument("--stdout", action="store_true", help="print instead of writing the file")
    l = sub.add_parser("lint", help="check the vault's rules")
    l.add_argument("vault", type=Path)
    args = ap.parse_args(argv)

    root: Path = args.vault.resolve()
    if not (root / "library").is_dir() or not (root / "mind").is_dir():
        print(f"{root} is not an expertise vault (needs library/ and mind/).", file=sys.stderr)
        return 2
    notes = load_vault(root)

    if args.cmd == "dashboard":
        today = parse_date(args.today) if args.today else dt.date.today()
        if today is None:
            print("--today must be YYYY-MM-DD", file=sys.stderr)
            return 2
        text = render_dashboard(analyze(notes, today))
        if args.stdout:
            sys.stdout.write(text)
        else:
            (root / "_dashboard.md").write_text(text, encoding="utf-8")
            print(f"wrote {root / '_dashboard.md'}")
        return 0

    findings = lint(notes, root)
    for f in findings:
        print(f"{f.level.upper():7} {f.rel}: {f.message}")
    errors = sum(1 for f in findings if f.level == "error")
    print(f"{len(notes)} notes, {errors} errors, {len(findings) - errors} warnings.")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
